### ISSUE TITLE
Not generating certain profiles

### ISSUE THREAD

**Issue by TheJesusFish** [Matt-Retrogamer/mister-rt4k-dv1-profiles-generator#7]
Just running through Super Attact Mode, I have noticed a couple of cores that didn't have a profile generated for them.

Most notable is GBC, but there was also some arcade cores (maybe alternates?) that weren't generated either.

I think the problem with GBC is that the Gameboy "core" is actually an MGL file. The retrotink still sees it as GBC and therefore needs a GBC.rt4k profile for it.

**Comment by Matt-Retrogamer** [comment]
Fixed 🙂
